FROM node:18.19.1-alpine3.19
EXPOSE 8080
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop
# now above cmd will adding the group & adding system user to the roboshop application 
# 1st we r creating roboshop group and now adding roboshop user to the roboshop group.
#This is group & users will be system users only not for normal users.
WORKDIR /opt/server
ENV MONGO=true
RUN chown roboshop:roboshop /opt/server
COPY package.json /opt/server/
COPY server.js /opt/server/
RUN npm install
USER roboshop
CMD ["node","server.js"]