FROM node:18.19-1-alpine3.19
EXPOSE 8080
WORKDIR /opt/server
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop
# now above cmd will adding the group & adding system user to the roboshop application 
# 1st we r creating roboshop group and now adding roboshop user to the roboshop group.
#This is group & users will be system users only not for normal users.
RUN chown roboshop:roboshop /opt/server
USER roboshop
ENV MONGO=true
COPY package.json /opt/server/
COPY server.js /opt/server/
RUN npm install
CMD ["node","server.js"]