FROM niginx:latest
RUN rm-rf /usr/share/nginx/html/index.html
#removing the default nginx conf
RUN rm -rf /etc/nginx/nginx.conf
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY roboshop.conf /etc/nginx/default.d/nginx.conf
ADD static /usr/share/nginx/html/